// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsuhpsjprxgtswwcpixk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzdWhwc2pwcnhndHN3d2NwaXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTYxODAsImV4cCI6MjA2MzQ5MjE4MH0.DdCk4RmC8jnmz-HaoMLvAU3LOIo9kKvazHo7hQrCT00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);